---
env:
  es2020: true
  jest/globals: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
  - jest
  - "@typescript-eslint"
  - deprecation
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
  - prettier
  - prettier/@typescript-eslint
rules:
  deprecation/deprecation:
    - warn
